version: "3.1"
services:
  node:
    build: .
    ports:
    - 8000:8000
    volumes:
    - .:/workspaceFolder
    working_dir: /workspaceFolder
    command: bash -c "dumi dev"
  mysql:
    image: mysql
    environment:
    - MYSQL_ROOT_PASSWORD=123456
    - MYSQL_DATABASE=java
    volumes:
    - $PWD/conf:/etc/mysql/conf.d
    - $PWD/logs:/logs
    - $PWD/data:/var/lib/mysql
    container_name: my-mysql
    ports:
    - "3306:3306"
