version: "3.1"
services:
  mysql:
    image: mysql:5.7
    environment:
    - MYSQL_ROOT_PASSWORD=123456
    volumes:
    - /usr/local/mysql/init:/docker-entrypoint-initdb.d/
    container_name: my-mysql
    ports:
    - "3306:3306"
